spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa_demo_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: public
        format_sql: true
    show-sql: true